Repository HackYourFuture/hyfer, pull requests merged in 2018-05, with the labels that each got.

#97 Adding popup feature
  package-lock.json
  server/api/update-email.js
  server/routes.js
  src/App.js
  src/components/Header/Header.js
  src/components/Popup/index.js
  src/store/TimeLineStore.js
  src/store/UiStore.js
  src/store/index.js
Labels: Still working on it

#101 :sparkles: adding new component to display the PRs that have open sta…
  src/components/Attendance/Attendance.js
  src/components/Attendance/CommitsInfo.js
Labels: review wanted, work in progress

#106 fixed popup appearing on every request
  src/components/Popup/index.js
Labels: bug fix

#94 Roles In Frontend
  package-lock.json
  server/api/github.js
  server/routes.js
  src/App.js
  src/Pages/Homework/Homework.js
  src/Pages/Homework/Reviews.js
  src/Pages/Modules/ModuleFooter.js
  src/Pages/Modules/ModuleServiceBack.js
  src/Pages/NotFound/index.js
  src/Pages/Timeline/TimeLine.js
  src/Pages/TrainTicket/TrainTicket.js
  src/Pages/Users/Profile.js
  src/Pages/Users/Users.js
  src/Pages/Users/currentUserProfile.js
  src/Pages/Users/userAccount.js
  src/components/Attendance/Attendance.js
  src/components/Header/Header.js
  src/components/Popup/index.js
  src/components/Users/SynchronizeGithubData.js
  src/components/timelineComp/Buttons/AddDropdownList/AddClassModal/AddClassModal.js
  src/components/timelineComp/Buttons/AddDropdownList/AddNewModuleModal/AddNewModuleModal.js
  src/components/timelineComp/ClassBarRowComp/ClassRowComp/ClassRowComp.js
  src/components/timelineComp/ClassTaskRowComp/DropdownList/AssignTeacherModal/AssignTeacherModal.js
  src/components/timelineComp/ClassTaskRowComp/DropdownList/DropdownList.js
  src/components/timelineComp/ClassTaskRowComp/TaskComp/TaskComp.js
  src/components/timelineComp/Timeline/Timeline.js
  src/notify.js
  src/store/ModuleInfoStore.js
  src/store/TimeLineStore.js
  src/store/UiStore.js
  src/store/UserStore.js
  src/util/index.js
Labels: Still working on it

#116 Decorate popup window
  package-lock.json
  src/App.js
  src/Helpers/Modal/Modal.js
  src/Pages/Homework/AssignReviewer.js
  src/Pages/Homework/ClassPage.js
  src/assets/styles/footer.css
  src/assets/styles/homework.css
  src/components/Popup/index.css
  src/components/Popup/index.js
Labels: review wanted
